version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      FLASK_APP: app.py
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    user: "1000:1000"
